//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetList.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobsApplied> JobsApplieds { get; set; }
        public virtual DbSet<tbl_Students> tbl_Students { get; set; }
        public virtual DbSet<UserJob> UserJobs { get; set; }
    
        public virtual ObjectResult<interview_GetStudentList_Result> interview_GetStudentList(string studentinstr)
        {
            var studentinstrParameter = studentinstr != null ?
                new ObjectParameter("studentinstr", studentinstr) :
                new ObjectParameter("studentinstr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<interview_GetStudentList_Result>("interview_GetStudentList", studentinstrParameter);
        }
    
        public virtual ObjectResult<string> interview_GetStudentName(Nullable<int> studentid)
        {
            var studentidParameter = studentid.HasValue ?
                new ObjectParameter("studentid", studentid) :
                new ObjectParameter("studentid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("interview_GetStudentName", studentidParameter);
        }
    }
}
