//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetList.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsApplied
    {
        public int id { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public bool Interview { get; set; }
    }
}
